title: Andrew Wang
logo: /assets/img/pfp.jpg
description: PhD student @ JHU CLSP
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
exclude: ['temp']
github:
  is_user_page: true
  is_project_page: false
  cv_url: ""
